// AUTO-GENERATED by NativeFlow auth-codegen. Do not edit by hand.

export type AuthStatus = 'idle' | 'authenticated' | 'unauthenticated' | 'expired';

export interface NormalizedUser {
  id: string;
  email: string | null;
  displayName: string | null;
}

/**
 * Roles are carried alongside permissions, not collapsed into them. A role
 * with no permissions expands to an empty list, which is indistinguishable
 * from "signed in, any role"; two roles sharing one permission are likewise
 * indistinguishable. Screen guards need the role names themselves.
 */
export interface Grants {
  roles: string[];
  permissions: string[];
}

export interface AuthState {
  status: AuthStatus;
  user: NormalizedUser | null;
  roles: string[];
  permissions: string[];
}

export type LoginInput =
  | { kind: 'password'; email: string; password: string }
  | { kind: 'oauth'; provider: string }
  | { kind: 'sso' };

export interface SignUpInput {
  email: string;
  password: string;
  displayName?: string;
}

/** Thrown when a screen calls a method the configured provider cannot do. */
export class AuthMethodUnsupportedError extends Error {
  constructor(public method: string, public provider: string) {
    super(method + ' is not supported by the ' + provider + ' provider');
    this.name = 'AuthMethodUnsupportedError';
  }
}

/**
 * A sign-in that stopped half way and needs one more answer.
 *
 * Deliberately provider-neutral: these are OUR names, not the backend's, so a
 * screen written against them keeps working if the backend changes.
 */
export type KnownChallengeName =
  | 'newPasswordRequired'
  | 'smsMfa'
  | 'totpMfa'
  | 'emailOtp'
  /** The backend offered a list of ways to finish signing in; the user picks one. */
  | 'selectChallenge'
  /** Passwordless sign-in: a code emailed to the account's address. */
  | 'emailOtpSignIn'
  /** Passwordless sign-in: a code texted to the account's phone number. */
  | 'smsOtpSignIn';

/**
 * Open on purpose. A backend we have never met can hand back a challenge name
 * of its own; the app routes anything it does not recognise to the generic
 * code-entry screen rather than dead-ending the sign-in.
 */
export type ChallengeName = KnownChallengeName | (string & {});

/**
 * An opaque handle to a half-finished sign-in.
 *
 * The provider's own session string is NOT in here. It is single-use, expires,
 * and can run to 8192 characters; the adapter keeps it privately and this
 * handle only names it, so nothing can truncate it, persist it, or push it
 * through a navigation param. Held in memory only — see lib/auth/challenge.ts.
 */
export interface PendingAuthSession {
  /** Lookup key into the adapter's private session table. */
  readonly id: string;
  readonly challenge: ChallengeName;
  /** Attributes the backend demands alongside the new password, if any. */
  readonly requiredAttributes?: string[];
  /** "we texted •••• 4421" — safe to show, never the full destination. */
  readonly deliveryHint?: string | null;
  /** Heading for the generic screen when the challenge name is unknown. */
  readonly title?: string;
  /** One line explaining why this step appeared, shown under the heading. */
  readonly reachedWhen?: string;
  /**
   * When the backend offered a CHOICE of ways to finish, the ways it offered.
   * Present only on a 'selectChallenge' handle; a single-challenge handle
   * leaves it undefined, which is why it is not a one-element array.
   */
  readonly availableChallenges?: ChallengeName[];
  /** Epoch ms after which the handle is dead and the user must start over. */
  readonly expiresAt: number;
}

/** What the user typed on a challenge screen. */
export interface ChallengeResponse {
  /** For a forced password change. */
  newPassword?: string;
  /** Any MFA / OTP variant. */
  code?: string;
  /** Attribute name → value, for attributes the backend required. */
  attributes?: Record<string, string>;
  /**
   * The option the user picked on a choice screen. Answering a
   * 'selectChallenge' handle carries this INSTEAD of a code: the backend is
   * being told which challenge to start, not being given an answer to one.
   */
  chosenChallenge?: ChallengeName;
}

/**
 * Either a finished session or the next challenge. Backends can chain them —
 * a forced password change on an MFA-enabled pool asks twice.
 */
export type AuthResult =
  | { kind: 'session'; state: AuthState }
  | { kind: 'challenge'; pending: PendingAuthSession };

/** Thrown by login() when the backend answered with a challenge, not tokens. */
export class AuthChallengeRequiredError extends Error {
  constructor(public pending: PendingAuthSession) {
    super('This sign-in needs one more step.');
    this.name = 'AuthChallengeRequiredError';
  }
}

/** Thrown when the pending handle has expired or was already spent. */
export class AuthChallengeExpiredError extends Error {
  constructor() {
    super('That took too long. Please sign in again.');
    this.name = 'AuthChallengeExpiredError';
  }
}

export interface AuthProvider {
  /** Identifies the backend in error messages. */
  readonly providerName: string;
  login(input: LoginInput): Promise<AuthState>;
  logout(): Promise<void>;
  getToken(): Promise<string | null>;
  refreshToken(): Promise<string | null>;
  getCurrentUser(): Promise<NormalizedUser | null>;
  /** Roles AND the permissions they expand to, resolved in one round trip. */
  getGrants(): Promise<Grants>;
  onAuthStateChange(cb: (state: AuthState) => void): () => void;

  /** Self-serve account creation. Absent when the backend has no sign-up API. */
  signUp?(input: SignUpInput): Promise<AuthState>;
  /** Send a one-time code to a phone number. */
  sendOtp?(phone: string): Promise<void>;
  /** Exchange a phone + code for a session. */
  verifyOtp?(phone: string, code: string): Promise<AuthState>;
  /** Email a passwordless sign-in link. */
  sendMagicLink?(email: string): Promise<void>;
  /** Email a password-reset link, or a reset code on code-based backends. */
  resetPassword?(email: string): Promise<void>;

  /**
   * Code-based backends only. Sign-up leaves the account
   * UNCONFIRMED and unusable until the emailed code is submitted here, so
   * these are separate methods rather than options on signUp.
   */
  confirmSignUp?(username: string, code: string): Promise<void>;
  resendConfirmationCode?(username: string): Promise<void>;
  /** Finish a code-based reset: the code plus the password it authorises. */
  confirmResetPassword?(username: string, code: string, newPassword: string): Promise<void>;

  /**
   * Answer a mid-sign-in challenge. Absent on every backend that never hands
   * the app a half-authenticated session — the hosted-page providers settle
   * MFA inside their own browser flow, so there is nothing here to answer.
   */
  respondToChallenge?(
    pendingSession: PendingAuthSession,
    challenge: ChallengeName,
    response: ChallengeResponse,
  ): Promise<AuthResult>;

  /**
   * Begin a sign-in with a code instead of a password.
   *
   * Returns a challenge, not a session: the code has just been sent and the
   * app has to collect it. A session is only possible on a backend that can
   * decide the user is already trusted, which is why the type allows both.
   */
  startPasswordlessSignIn?(
    username: string,
    method: 'emailOtp' | 'smsOtp',
  ): Promise<AuthResult>;

  /**
   * Send the current code again. Returns the REPLACEMENT handle — a resend
   * generally invalidates the old session string, so answering with the
   * previous handle would fail.
   */
  resendChallengeCode?(pendingSession: PendingAuthSession): Promise<PendingAuthSession>;
}
